language: c
sudo: required
dist: xenial
cache: ccache

before_install:
  # sudo add-apt-repository ppa:ddalex/gstreamer -y # gstreamer-1.4.3
  # sudo add-apt-repository ppa:dan-witt/gstreamer -y # gstreamer-1.6.3
  - sudo apt-get update -qq
  - sudo apt-get install -y gdb gtk-doc-tools libglib2.0-dev libgsf-1-dev libgtk-3-dev libclutter-1.0-dev libclutter-gtk-1.0-dev gstreamer1.0-tools gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-alsa libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgudev-1.0-dev liborc-dev libasound2-dev check libfluidsynth-dev libxml2-utils libgstreamer1.0-0-dbg gstreamer1.0-plugins-base-dbg libglib2.0-0-dbg libgtk-3-0-dbg yelp-tools

before_script:
  - ./autogen.sh --noconfigure

env:
  - CONFIGURE_OPTS="--enable-debug --enable-coverage"
  - CONFIGURE_OPTS="--disable-debug"

script:
  - ./configure ${CONFIGURE_OPTS} && make && travis_wait make check

after_failure:
  - cat ./bt_edit.log ./test-suite.log && scripts/gdbtests.sh ./test-suite.log

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  irc: "chat.freenode.net#buzztrax"

addons:
  artifacts:
    paths:
    - test-suite.log
    - bml.tar.bz2
    - bt_cmd.tar.bz2
    - bt_core.tar.bz2
    - bt_edit.tar.bz2
    - bt_gst.tar.bz2
    - bt_ic.tar.bz2
    - $(ls /tmp/record.* | tr "\n" ":")

