#!/bin/sh
# Shell script to download the latest translations from translationproject.org


# LANGUAGES based on http://translationproject.org/extra/matrix.html
# We need to check all languages, not only po/LINGUAS, since there might be
# new translations
LANGUAGES=\
"af am ar az be bg pt_BR bs ca zh_CN cs cy da de el eo es et eu fa fi fr "\
"ga en_GB gl gu he hi zh_HK hr hu id is it ja ko ku ky lg lt lv mk mn ms "\
"mt nb ne nl nn or pa pl pt rm ro ru rw sk sl sq sr sv ta tq th tk "\
"tr zh_TW uk ven vi wa xh zu"

# for testing/debugging:
#LANGUAGES="es fr hu sv pl xx"

# check for 'diff' program
diff --version 2>/dev/null >/dev/null
if [ $? -ne 0 ]; then
  echo "==== You must have the 'diff' program installed for this script ===="
  exit 1
fi

# check for 'wget' program
wget --version 2>/dev/null >/dev/null
if [ $? -ne 0 ]; then
  echo "==== You must have the 'wget' program installed for this script ===="
  exit 1
fi

# check for 'msguniq' program
msguniq --version 2>/dev/null >/dev/null
if [ $? -ne 0 ]; then
  echo "==== You must have the 'gettext' package installed for this script ===="
  exit 1
fi

# make sure we're in the top-level directory
if [ ! -d ./po ]; then
  echo "==== No ./po directory in the current working directory ===="
  exit 1
fi

DOMAIN="buzztrax"

LANGUAGES_TO_ADD=""
LANGUAGES_UPDATED=""

echo "Downloading latest translation files for domain $DOMAIN ..."
echo

for l in $LANGUAGES
do
  DOMAIN_PO_URL_BASE="http://translationproject.org/latest/$DOMAIN"
  PO_URL="$DOMAIN_PO_URL_BASE/$l.po"
  PO_FILENAME="$DOMAIN.$l.po"
  if wget -q -nc -O $PO_FILENAME $PO_URL; then
    # we want all .po files in UTF-8 format really, so convert if needed..
    CHARSET=`grep Content-Type $PO_FILENAME | sed -e 's/.*charset=\(.*\)\\\\n.*/\1/'`
    if test "x$CHARSET" != "xUTF-8" -a "x$CHARSET" != "xutf-8"; then
      # note: things like the bugs address will be added back by make update-po
      if msguniq $PO_FILENAME --no-location \
                              --output-file=$PO_FILENAME.utf8 \
                              --to-code=UTF-8; then
        mv $PO_FILENAME.utf8 $PO_FILENAME
      else
        echo "**** $l: conversion from $CHARSET to UTF-8 failed ****"
      fi
    fi
    if [ -f "po/$l.po" ]; then
      # ./po/foo.po exists, so let's check if ours matches the latest from the
      # translation project website
      REVDATE_NEW=`grep PO-Revision-Date $PO_FILENAME`;
      REVDATE_OLD=`grep PO-Revision-Date po/$l.po`;
      CHARSET_OLD=`grep Content-Type po/$l.po | sed -e 's/.*charset=\(.*\)\\\\n.*/\1/'`
      if test "x$REVDATE_NEW" = "x$REVDATE_OLD" -a "x$CHARSET_OLD" = "xUTF-8"; then
        # note: source code line markers will be removed later by make upload-po
        echo "$l.po: up-to-date"
        rm -f $PO_FILENAME
      else
        mv $PO_FILENAME "po/$l.po"
        if test "x$CHARSET_OLD" != "xUTF-8" -a "x$CHARSET_OLD" != "xutf-8"; then
          echo "$l.po: update (and charset converted from $CHARSET_OLD to UTF-8)"
        else
          echo "$l.po: updated"
        fi
        LANGUAGES_UPDATED="$LANGUAGES_UPDATED $l"
      fi
    else
      # ./po/foo.po doesn't exist, but foo.po exists on the translation project
      # website, so it's probably a new translation
      echo "$l.po: new language"
      mv $PO_FILENAME "po/$l.po"
      LANGUAGES_TO_ADD="$LANGUAGES_TO_ADD $l"
    fi
  else
    rm -f $PO_FILENAME
    echo "$l.po: failure (probably does not exist yet)"
  fi
done

if [ -n "$LANGUAGES_UPDATED" ] || [ -n "$LANGUAGES_TO_ADD" ]; then
  echo "===================================================================="
  echo
  echo "Language codes updated    :$LANGUAGES_UPDATED"
  echo "Language codes to git add :$LANGUAGES_TO_ADD"
  echo
  echo "Source: http://translationproject.org/latest/$DOMAIN/"
  echo
  if [ -n "$LANGUAGES_UPDATED" ]; then
    CMD_STRING="git add"
    for l in $LANGUAGES_UPDATED; do
      CMD_STRING="$CMD_STRING po/$l.po"
    done
    CMD_STRING="$CMD_STRING; git commit -m 'po: update translations'"
    echo "To commit the updated translations, please run:"
    echo
    echo "  $CMD_STRING"
    echo
    echo
  fi
  if [ -n "$LANGUAGES_TO_ADD" ]; then
    echo "Edit 'po/LINGUAS' adding the following new language codes:"
    echo
    echo "  $LANGUAGES_TO_ADD"
    echo
    CMD_STRING="git add"
    for l in $LANGUAGES_TO_ADD; do
      CMD_STRING="$CMD_STRING po/$l.po"
    done
    CMD_STRING="$CMD_STRING po/LINGUAS; git commit -m 'po: add new translations'"
    echo "and now add the new translations, please run:"
    echo
    echo "  $CMD_STRING"
    echo
    echo
  fi
  echo "===================================================================="
fi


