name: Build

on:
  push:
    branches:
     - 'main'
  pull_request:
    branches:
    - 'main'
  workflow_dispatch:

permissions:
  contents: read

env:
  CONFIGURE_OPTS: "--enable-debug --enable-coverage --disable-debug"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y gdb gtk-doc-tools libglib2.0-dev libgsf-1-dev libgtk-3-dev libclutter-1.0-dev libclutter-gtk-1.0-dev gstreamer1.0-tools gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-alsa libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgudev-1.0-dev liborc-dev libasound2-dev check libfluidsynth-dev libxml2-utils libgstreamer1.0-0-dbg gstreamer1.0-plugins-base-dbg libglib2.0-0-dbg libgtk-3-0-dbg yelp-tools

    - name: Build
      run: |
        ./configure ${{ env.CONFIGURE_OPTS }}
        make
        make check

    - uses: action/upload-artifact@v4
      with:
        path: |
          test-suite.log
          bml.tar.bz2
          bt_cmd.tar.bz2
          bt_core.tar.bz2
          bt_edit.tar.bz2
          bt_gst.tar.bz2
          bt_ic.tar.bz2
          /tmp/record.*
          
    - name: Rerun failed tests under gdb and get backtraces
      if: failure()
      run: |
        cat ./bt_edit.log ./test-suite.log
        scripts/gdbtests.sh ./test-suite.log
